### ISSUE TITLE
Remove custom secondary wallet for PIN validation

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1161]

**Comment by jleach** [comment]
I've looked into this and the 2nd wallet isn't actually a different wallet. We just have one wallet on the phone. What we have is two methods to do authentication: 1) If the user users biometrics then we have the wallet key stored in secure encrypted storage protected by the device's biometrics. Because we know the key is legit we can pass it directly to the splash screen to unlock the wallet during agent initialization. 2) if the user is using a PIN then we only have the "salt" store in the keychain. We compute the hash and need to verify its legit by unlocking the wallet. In both cases its the same wallet.

I think we can close this. If anything perhaps we can use the unlocked wallet for the PIN to pass into the agent but I don't believe this is an option with AFJ at the moment.

**Comment by jleach** [comment]
I think Timo and I agree there is only one wallet. Closing.
