### ISSUE TITLE
Unable to use LSBC demo credential

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1166]
### Description of problem

When logging onto access court materials with the LSBC demo credential the app hangs at the proof screen. The version from the AppStore works as expected.

### Expected behavior

The proof screen should be displayed.

### Steps to reproduce

1. Issue a demo LSBC credential form the LSBC site
2. Use the credential to access court materials.

### Screenshots and/or log output

https://images.zenhubusercontent.com/429950091/945702ae-0b00-4854-a0e2-4b3afd359c4c/lsbcnotworking.mov

### Environment
- [ ] Occurs on Android
- [ ] Occurs on iOS

Build #:

Tested with build 1.0.9 955 from TestFlight. The version in the AppStore works as expected.

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by wadeking98** [comment]
I've figured out the cause of this issue. The issue appears to be in AFJ since execution never passes the `agent.proofs.retrieveRequestedCredentialsForProofRequest()` function while the proof detail screen is stalled. I tested issuing a couple proof request and it seems like if you have the revocation from interval set to 0 then it hangs. This seems to be because AFJ treats `from: undefined` and `from: 0` differently. If from is undefined then AFJ only checks that it hasn't been revoked up until the time specified by `to`. However, if `from` is set to 0 then it seems like AFJ tries to scan the revocation registry from the beggining of time. I believe it's this intensive scan that causes the proof detail screen to hang. I've tried this out in traction and my findings support this idea:

## Traction Proof 1: (Doesn't hang):
```json
{
"name": "Member Card",
"nonce": "1234567890",
"requested_attributes": {
	"Person Credential": {
		"names": [
			"Member Status"
		],
		"non_revoked": {
			"to": 1685395156
		},
		"restrictions": [
			{
				"schema_name": "Member Card"
			}
		]
	}
},
"requested_predicates": {},
"version": "1.0"
}
```

## Traction Proof 2: (Hangs):
```json
{
"name": "Member Card",
"nonce": "1234567890",
"requested_attributes": {
	"Person Credential": {
		"names": [
			"Member Status"
		],
		"non_revoked": {
			"to": 1685395156,
                        "from": 0
		},
		"restrictions": [
			{
				"schema_name": "Member Card"
			}
		]
	}
},
"requested_predicates": {},
"version": "1.0"
}
```

note the only difference between the two requests is the `from: 0` attribute.

For LSBC to fix the proof request, simply remove the `from: 0` from the proof request non-revocation interval

**Comment by jleach** [comment]
@wadeking98 Top-notch sleuthing!

**Comment by swcurran** [comment]
Some background on this can be found in [RFC 0441 Present Proof Best Practices](https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0441-present-proof-best-practices).  When a verifier asks for an interval range, they are saying “I’ll accept a non-revocation proof any time from \<from> to \<to>”. If you see from “0”, you are saying from the start of time, which means that the holder can use the RevReg state at the time the credential was first issued, which of course will also be “Not Revoked”.  In general, “from” should not be included or should equal “to”, and in the common case should be “now()”.  

Why is interval there vs. a single number?  It’s a pretty obscure use case IMHO.  If the verifier is offline, and they have cached a bunch of RevReg State entries — say all of the ones for the last week — they can send an interval to ensure that the holder uses one of those RevReg states.  Supporting that use case (which is likely not used by anyone…) has caused tons of problems like this one.

**Comment by jleach** [comment]
@swcurran Ty. What does it mean if the `from:` is missing. Would it be interpreted as 0, now, or equal to `to:`?

**Comment by swcurran** [comment]
Per [this section of RFC 0441](https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0441-present-proof-best-practices#semantics-of-non-revocation-interval-endpoints), a missing `from` is set equal to `to` in Aries.

**Comment by jleach** [comment]
Perfect, I think AFJ is doing the right thing then. Below, `true` would trigger an exception. We just need to wait for `vc-autn-oidc` v2 to be release so we can remove our hack (tracked via #1191).

```console

> let withZeroFrom = { from: 0, to: 12345 }
> let withNotZeroFrom = { from: 555, to: 12345 }
> let noFrom = { to: 12345 }
> let fromAndToMatch = { from: 12345, to: 12345 }
>
> ((withZeroFrom.from || withZeroFrom.from === 0) && withZeroFrom.to !== withZeroFrom.from)
true
> ((withNotZeroFrom.from || withNotZeroFrom.from === 0) && withNotZeroFrom.to !== withNotZeroFrom.from)
true
> ((noFrom.from || noFrom.from === 0) && noFrom.to !== noFrom.from)
false
> ((fromAndToMatch.from || fromAndToMatch.from === 0) && fromAndToMatch.to !== fromAndToMatch.from)
false
```
