### ISSUE TITLE
Spike: Responsive Design/UX in react native

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1215]
Testing the app in a tablet, identify any issues.

Focus: Android

Outcome: Issues added to the backlog

**Comment by nodlesh** [comment]
Video of the app running on Android Galaxy Tab S5e
https://images.zenhubusercontent.com/429950091/fd3c2e26-0dff-455c-9889-5b63c2481a5b/samsunggalaxytabs5e_build868_480.mov

**Comment by bryce-mcmath** [comment]
Tested on Android Tablets. Three main issues:
1) Bottom tabs navigation on most tablets is messed up (see attached screenshot)
![Screenshot 2023-06-30 at 1.19.36 PM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/7eb11f80-5cb0-43f0-bb91-c4bdbe7e337e) 
2) Credential branding is not being applied the same as it is on phones (see attached screenshots)
![Screenshot 2023-06-30 at 1.33.42 PM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/0f726f49-616d-4b59-96f6-6d78967d28b7)
![Screenshot 2023-06-30 at 1.23.34 PM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/6009f01f-ca97-444a-8895-206da717f982)
3) Font size is quite small. There are a couple of different approaches if we want to account for this. I will lay those out further down.

3.5 It's also worth noting that it took a long time to make connections, receive credentials, and receive proof requests. Not sure if this was because of the device type or if the showcase was just having a bad day.

Most of the stuff you can do to make your RN app responsive we are already doing. Things like using flex and percentages and window dimensions. But there are a couple of neat tricks I found for taking it further. There is an API for iOS, `Platform.isPad` but no such equivalent exists for Android. 

In place of that, because our app is restricted to portrait mode, we might be able to determine if a device is a tablet, by using the aspect ratio. Then we could conditionally apply styling based on some boolean that aspect ration is greater than or equal to some number (whatever the lowest aspect ratio for tablet is.) 

Another technique I found, is calculating a scale like so for using in your styling:
```
import { Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const guidelineBaseWidth = 375;
const guidelineBaseHeight = 812;

const horizontalScale = (size) => (width / guidelineBaseWidth) * size;
const verticalScale = (size) => (height / guidelineBaseHeight) * size;
const moderateScale = (size, factor = 0.5) => size + (horizontalScale(size) - size) * factor;

export { horizontalScale, verticalScale, moderateScale };
```
Where `moderateScale` is used for things like font size and the horizontalScale and verticalScale are used for their respective sizing properties (`marginLeft` etc.)

A third option is to just recommend that users increase their font/zoom settings prior to using the app, but I'm not sure how I feel about that. Saves us a lot of work but kind of puts it on the user.

**Comment by bryce-mcmath** [comment]
I believe in order to get similar results on iOS we would need to add support for iPads by adjusting the following settings in Xcode:![Screenshot 2023-06-30 at 3.31.50 PM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/d02cb41b-2f40-4f93-80fb-06bac2fc1937)

**Comment by hiteshgh** [comment]
Assigned back to @bryce-mcmath to confirm if desired Spike outcomes are achieved , if yes close

**Comment by bryce-mcmath** [comment]
I'm going to leave this in done so that we can still refer to it
