### ISSUE TITLE
Edit Wallet Name Pencil icon on Scan my QR code page missing Test id on Android

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1632]
### Description of problem
On Android devices, on the Scan buy QR Code page, there is no test id for the pencil icon that represents edit wallet name.

### Expected behavior
Expected to see the `com.ariesbifold:id/EditWalletName` as I do on iOS. 

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS

Build #: 1326

Android Device Model: All

iOS Device Model: 

### Workaround
Currently using the accessibility label to get the element. 

### Severity
- [ ] High
- [ ] Medium
- [x] Low
- [x] 

### Scope
- Investigate how to setup and use Appium to inspect test ID
- Maybe loook into alternatives like https://reactnative.dev/docs/react-devtools
- https://fbflipper.com/docs/features/

**Comment by cvarjao** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BC-Wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/1632?planning-poker) with Zenhub @jleach @wadeking98 @bryce-mcmath

**Comment by bryce-mcmath** [comment]
Our usual Appium process doesn't seem to like our setup anymore and fails to run. Instead I tried both react-devtools and the standard "Debug View Hierarchy" for both Android Studio and Xcode. react-devtools showed a testID that isn't making it into the Android release build, so that doesn't help, and the Debug View Hierarchy Android equivalent doesn't work either. There is a promising Flipper plugin, "Inspecting native layout elements" that might be useful but we removed Flipper because it was causing us issues, not sure if those issues are still present since upgrading our RN version. @jleach wanted to spend a bit of time on this so I'll reassign to him

**Comment by jleach** [comment]
I got it working using the `WebDriverAgent` which I've used in the past. I thought there was a new component that I tried and failed with called `XCUITest`. In any case its working now with `WebDriverAgent`. 

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/ba4be723-b53d-4451-b593-e91c4666eb4f)

**Comment by jleach** [comment]
I'll need to part this ticket until my replacement Android development devices shows up in a week.

**Comment by jleach** [comment]
I can see something with `resource-id` set to `com.ariesbifold:id/EditWalletName` on Android. Is this just not accessible or am I on the wrong screen?

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/00c02451-bee2-4491-8d15-4673b4e137c1)

**Comment by jleach** [comment]
Welp. I can't get it to show if I use a `TouchableOpacity` but if I switch it to be `Pressable` it just works. I'll fool with it a bit more but if I can't get it to fix within an hour of fool'n I'll make this change.

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/390891/4ea49863-ca2a-43b7-a221-f33fcb05b72f)

**Comment by jleach** [comment]
@nodlesh Able to re-test this one?

**Comment by nodlesh** [comment]
Though I couldn't get the testID to show in Appium Inspector on a Sauce Labs device manually, I did update the test code to use the testID on Android and it now appears to be working. This is build 1538.
