### ISSUE TITLE
Goal Codes flow for credential and proof still has the contact screen display

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#1656]
When using Goal Codes in QR Code invites for either cred issuance or proofs, as in the BC Wallet Demo Showcase, still has the contact screen flicker onto the screen for a fraction of a second. It almost feel like a glitch rather than part of the flow. Maybe we should not go to the Contact screen? 

However, what if the request or proof never comes, even if it was the goal? In that case it should go to the Contact screen.

See attached video for how it now behaves. 

https://github.com/bcgov/bc-wallet-mobile/assets/44370861/6c62db2f-9c1e-4acb-b92d-e57e18cd2fd7

### Severity
Low

**Comment by wadeking98** [comment]
I'm taking a look at the code right now, so it looks like the flicker is on the connection screen rather than the contact screen. The loading screen is a part of the Connection screen. I definitely agree it looks clunky but I don't think the issue has to do with the navigation. I think the waiting screen is a modal or something that gets animated after the connection screen is mounted. I'll remove the header from the connection screen and fixup the modal and that should get rid of the issue

**Comment by wadeking98** [comment]
I can't seem to reproduce this anymore, are you still able to @nodlesh ?
