### ISSUE TITLE
Missing app icon on push notification (android)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1820]
### Description of problem
![signal-2024-02-23-132424](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/d17dbbed-120a-43f3-89c5-d4c7e0cd739c)

### Expected behavior
![signal-2024-02-23-132437](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/dbdedfe1-8fec-4505-bccc-bb43912ba073)

### Steps to reproduce
- Enable push notifications from dev mode
- Use mobile verifier for to connect to another phone, check for successful connected (test with a chat message)
- background the app (switch to another app, or go to to device home screen)
- send a message from the other device

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS (no)

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by bryce-mcmath** [comment]
A PR with a fix is up, but just to document it here, this is some relevant reading for future Android icon work: 
https://doc.batch.com/android/advanced/customizing-notifications/
https://github.com/zo0r/react-native-push-notification/issues/1326

The main takeaway is that to consistently work across all Android devices, the icon must be white with a transparent background. This is unfortunate because on some Android devices, the full colour image was working as an icon, but it was broken on others (white square.)

**Comment by jleach** [comment]
Verified in latest build.
