### ISSUE TITLE
Credential detail missing information

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#183]
credential details is missing:
- Issuer name
- Issued date in the details section is not in human readable format. it should reflect the same format as seen in the credential

![20220224_172941.png](https://images.zenhubusercontent.com/619bd30a068b26108b1bc2fe/fa79fbaf-0b19-49a7-865e-7620b636a1ac)

**Comment by amanji** [comment]
The challenge with the attribute values is we don't know if they are date/timestamps unless specified in the attribute type field.

**Comment by jleach** [comment]
@knguyenBC We might be able to do something about the date format. Milage may vary depending pin if its in full ISO 8601 format or not otherwise we need a hint as @amanji mentions above. Also, I don't see the issuer info in the design (screen shot below). Its in the offer screens, because it says `Blah is offering you...` The `Issued By` field in the screen shot below would only appear **if** the issuer puts in there. None of our demos include it that I know of.


![Screen Shot 2022-02-28 at 3.45.41 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/299153bf-561f-4400-a45b-a0282a547c77)

**Comment by knguyenBC** [comment]
Is it possible to add Issuer name into the credential detail list even though it's not part of the credential data?

**Comment by jleach** [comment]
We can make it look that way bit I don't like the idea. I think a VC should only display attributes that exist within it. For production credentials, we can ask that it be added for good measure.

**Comment by knguyenBC** [comment]
In regards to the conversation we had in rocketchat. The conclusion is that we'll mark this ticket as done and add another ticket to display issuer name.
