### ISSUE TITLE
Change OCA Bundle server location

### ISSUE THREAD

**Issue by swcurran** [bcgov/bc-wallet-mobile#1878]
The location where OCA Bundles are loaded should be updated to: `https://bcgov.github.io/aries-oca-bundles/`. This is the location where the OCA Bundle files are now published by a GitHub Action. Links:

- The index: [https://bcgov.github.io/aries-oca-bundles/ocabundles.json](https://bcgov.github.io/aries-oca-bundles/ocabundles.json)
- The bundles, such as [https://bcgov.github.io/aries-oca-bundles/OCABundles/schema/bcgov-digital-trust/LCRB/selling-it-right-showcase/OCABundle.json](https://bcgov.github.io/aries-oca-bundles/OCABundles/schema/bcgov-digital-trust/LCRB/selling-it-right-showcase/OCABundle.json) that are listed in the index.

The index file in the location being used now is only being manually updated.

**Comment by jleach** [comment]
I've updated my local `.env` and it works as expected. I see branding for the Student card and Person credential. So I went ahead and updated in our build. The change should come out with the next 1.0.21 beta.

@bryce-mcmath FYI.

**Comment by bryce-mcmath** [comment]
Tested, is working as expected

**Comment by swcurran** [comment]
@bryce-mcmath — thanks for getting this done.  We’re going to follow on with an update to the OCA Bundle repository to remove the generated files from the repository main branch — having them only on the gh-pages branch/site.

Could you please summarize for us how the resolving/caching works in BC Wallet/Bifold with the OCA Bundles?  If an OCA Bundle moves, for example, will the wallet detect such a change and load the bundle dynamically?

**Comment by swcurran** [comment]
Also — add a comment here when the feature is in the released BC Wallet, so we know when we can start to adjust the repo GitHub Actions.

**Comment by bryce-mcmath** [comment]
@swcurran I just tested that it was working in Testflight, @jleach is the one that made the change. But we haven't done a release since this change, so existing release wallets will still be using the old URL until then. So please hold off from removing that for the time being.

The way it works is there is a BC Wallet OCA_URL env var that the app makes a GET to and caches the response from, and then checks on app startup if the response is any different or stale, and if so, refetches. But it doesn't dynamically search different URLs.

**Comment by jleach** [comment]
Confirming what @bryce-mcmath said above. It will "refresh" when it checks the new URL as needed. But, any version prior to 1.0.21 will still need the old URL to apply branding. My though is you can "archive" the old OCA repo once 1.0.21 is out and over time it will just become less and less used as version upgrade. If you actually want to delete it maybe give it several weeks / months.

**Comment by swcurran** [comment]
When you say “on app startup” — I assume that means each time the user opens the app? 

What does the app cache — only the JSON list of identifiers/bundles, or does it also retrieve and cache all the bundles referenced in the JSON list?

Thanks

**Comment by swcurran** [comment]
What we are planning is that the repo hold only the source files, and the generated files (OCA Bundles, the JSON List of Bundles) are only in the new location.  That will make it much easier on those managing OCA Bundles.

By the way, does Bifold/BC Wallet have the capability of having multiple OCA_URLs?  That might be useful.

**Comment by jleach** [comment]
> When you say “on app startup” — I assume that means each time the user opens the app?

Yes, in the splash screen it does a check.

> What does the app cache — only the JSON list of identifiers/bundles, or does it also retrieve and cache all the bundles referenced in the JSON list?

It caches the index file (since that links a schema or cred deff to the bundle), and the bundles. It does so based on the [etag](https://en.wikipedia.org/wiki/HTTP_ETag). If the etag changes will will re-fetch a bundle (or the index).

As a side note we may need to extend the cache to include graphical assets. 

> By the way, does Bifold/BC Wallet have the capability of having multiple OCA_URLs?  That might be useful.

Nope. 

> What we are planning is that the repo hold only the source files, and the generated files (OCA Bundles, the JSON List of > Bundles) are only in the new location. That will make it much easier on those managing OCA Bundles.

This is fine but like I mention above: Anyone on < 1.0.21 will still have the old URL hard coded in their release so we should wait several weeks to let update trickle through.

**Comment by swcurran** [comment]
To confirm — we have waited the necessary few weeks and can confirm the new URL is being used in the released BC Wallet — and we won’t break anything if we remove the files in the old places?

**Comment by jleach** [comment]
> To confirm — we have waited the necessary few weeks and can confirm the new URL is being used in the released BC Wallet — and we won’t break anything if we remove the files in the old places?

Confirmed.
