### ISSUE TITLE
Unable to delete old credentials (pre W3C/Credo 0.5)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1952]
### Screenshots
![Image](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/f0b1dd83-6b6a-4847-8cee-495ec2c229f6)

![Image](https://github.com/bcgov/bc-wallet-mobile/assets/1348549/b172eab2-4b54-4e5d-b661-ff9ec0955956)

**Comment by esune** [comment]
### Description of problem
When trying to remove credentials from the wallet, BC Wallet raises an error.

On the first attempt to remove the credential, the error raised says it is an unsupported credential record type - requires w3c.
On subsequent attempts, the error says the credential exchange record does not exist.

Might be related to https://github.com/bcgov/bc-wallet-mobile/issues/1951 and the introduction of Credo 0.5 as a dependency.

### Expected behavior
Credentials can be removed from the wallet without issues.

### Steps to reproduce
1. Open BC Wallet
2. Receive one or more credentials
3. Attempt to delete one of the credentials

### Environment
- [x] Occurs on Android
- [ ] Occurs on iOS - unsure, don;t have a device to test with.

Build #: 1.0.17 (1676)

Android Device Model: Pixel 6 Pro

**Comment by jleach** [comment]
Fixed, tested with 1.0.16 -> 1.0.16 1740 with Showcase lawyer credentials issued in 1.0.16.
