### ISSUE TITLE
Revocation delay

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#2064]
### Description of problem
The reissuance of both the Person credential and the LSBC member credential does NOT revoke the older credential immediately. 
- The wallet displays the credential as non-revoked
- can be used in proof request and information will send successfully.
- The proof will fail however, with VC-AuthN displaying a proof not accepted error
- and the mobile verifier will display a "proof declined" screen on the verifier side. 
 
Oddly enough, for the Person credential, the revocation message sent over the connection will be sent.

### Expected behavior
Credentials should revoke immediately after issuance of the new ones

### Steps to reproduce
- obtain a person credential on device A
- Get another one on device B
- Check both are still non-revoked
- Attempt to use the Person credential from device A

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 1792

Android Device Model: Pixel 8

iOS Device Model: iPhone SE

### Workaround
none

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by WadeBarnes** [comment]
There is a long standing issue with the LSBC agent's wallet that started a few years back with an out of sync issue.  Revocation entries were created, but they could not be written to the ledger, so the wallet and the ledger got out of sync.  Ian created a fix that allowed us to sync the records retroactively.  This allowed us to permanently fix LSBC's DEV and TEST instances, however we were unable to permanently fix the issue in PROD.  A second fix (workaround) was put in place in aca-py so it automatically invoked the retro-active resync code whenever there was an error writing a revocation entry to the ledger.

Not saying it's the case, but you might be seeing a possible side affect due to this process.  To rule this out as an issue we'd need to monitor the ledger and see if there are any timing issues with revocation entries being written to the ledger during the revoke and re-issue process.

**Comment by cvarjao** [comment]
@WadeBarnes , @esune , this something that your  team can track. I don't think this is related to the wallet app.

**Comment by esune** [comment]
We can surely help track this down. I wonder however if the fact that the credential is not flagged as revoked in the wallet has to do with not receiving the revocation notification for some reason and/or at not being aware the credential is revoked if the ledger is not checked since the proof fails (note: I do not know exactly how the "prepare to respond to proof" step works in BC Wallet so I am speculating).

**Comment by jleach** [comment]
@esune IIRC the wallet will only care if the proof asks for a non-revoked credential. If the proof does not specify then the wallet won't care which makes sense. For example, just because a persons DL is expired does not mean it can't be used to proof someone is over 19. If the proof does specify not revoked then the wallet won't find a match.

**Comment by knguyenBC** [comment]
Would the wallet not display that its revoked in the proof request though?

**Comment by jleach** [comment]
@knguyenBC I'd have to confirm.

**Comment by esune** [comment]
> [@esune](https://github.com/esune) IIRC the wallet will only care if the proof asks for a non-revoked credential. If the proof does not specify then the wallet won't care which makes sense. For example, just because a persons DL is expired does not mean it can't be used to proof someone is over 19. If the proof does specify not revoked then the wallet won't find a match.

That makes sense. I can't recall exactly what I was thinking when I posted my comment, but I *think* I was referring to the credential appearing as revoked in the BC Wallet when the holder checks it, rather than in a proof request process (i.e.: I see the "revoked" red warning in my wallet when I open up the card).
