### ISSUE TITLE
Information missing from notifications

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#2200]
The following is a proof request screen shot from "Cool Clothes Online". The notification details are missing:

![Image](https://github.com/user-attachments/assets/321d41d0-2531-45b9-95b9-a816b1ee3419)

**Replication Procedure**

- Run through one of the sample cases in the BC Wallet Demo (https://bc-wallet-demo-test.apps.silver.devops.gov.bc.ca/digital-trust/showcase/)
- Once you hit the 'Start Proving' step, scan your credential.
- When you see the option to share your information, navigate directly back to the home screen by tapping the home button in the header

**Observed Behavior**

- A notification appears with no content and only a 'view' button (see above screenshot)

**Expected Behavior**

- Information about the proof request (e.g. Who the requests from, etc.)

**Comment by jeznorth** [comment]
**Replication Procedure**

- Run through one of the sample cases in the BC Wallet Demo (https://bc-wallet-demo-test.apps.silver.devops.gov.bc.ca/digital-trust/showcase/)
- Once you hit the 'Start Proving' step, scan your credential.
- When you see the option to share your information, navigate directly back to the home screen by tapping the home button in the header

**Observed Behavior**

- A notification appears with no content and only a 'view' button.

**Expected Behavior**

- Information about the proof request (e.g. Who the requests from, etc.)

**Comment by bryce-mcmath** [comment]
Is also reproducible with other proof request flows, (ie. Animo showcase) so it's a wallet problem, not a showcase one.

**Comment by jeznorth** [comment]
@bryce-mcmath This appears to be resolved - 1.0.21 (1936)
