### ISSUE TITLE
Inconsistent proof request flow for different demos

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/bc-wallet-mobile#359]
Every demo has a different experience using BC Wallet

### Animo demo (doesn't work)
- Android. Accepting a proof request doesn't work. Displays a "unable to accept proof request" error. [See video](https://images.zenhubusercontent.com/429950091/4ab0e625-1b4c-4d5f-8db2-2ae303c3687e/20220524_0943027385.mp4) 
- iOS. "Connecting..." modal hang after scanning a proof request QR code.
- iOS. Accepting a proof request does work. The screen bounces from the "sending..." modal back to the request UI automatically. [See video](https://images.zenhubusercontent.com/429950091/e90ba19b-e777-4150-bc3b-1e31c84942ea/20220524_1503178587.mp4) 

### BC Wallet demo
- Android. Proof request flow hangs on the "sending information" modal even after information has been sent successfully
- iOS. Credential offer hangs on "connecting..." modal. 
- iOS. Proof request hands on "connecting..." modal
- iOS. "Information sent successfully..." modal hangs even after successful proof request.

### Access to court materials
- Android only. After opening a proof request notification, a "unable to accept proof request" error appears prior to the requested information loading. Once the error is dismissed, the requested info loads and the flow continues as intended. [see ticket #358](https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/bcgov/bc-wallet-mobile/358).

- on iOS only. Proof request flows hangs on the "connecting..." modal after scanning the QR code. [See video](https://images.zenhubusercontent.com/429950091/9ae61aaa-5fa7-48bf-a775-04d3a1ee61be/20220524_1447473559.mp4)

**Comment by jleach** [comment]
@knguyenBC I didn't test the Animo demo because @amanji noted there was an error with credential definition is not published. Will skip for now.

As of build 185 the hang on the connection screen should be fixed.

I tested the **BC Wallet** demo. The proof hangs for me on "Information sent successfully" because, even though we have a connection (connectionId !== undefined) the proof never gets past `presentation-sent`. The wallet is waiting for this. When I try the Faber demo, it works as expected.

The missing message is the ACK.  For ref, this is the message the wallet is expecting (from the Faber demo):

```JSON
 INFO  INFO: Received message with type 'did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/ack' from connection 5e50b5aa-70e6-44cf-ac54-91121c863d9e (faber.agent) {
  "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/ack",
  "@id": "4f85503b-91c3-4402-bfe9-f68d4b0b5109",
  "~thread": {
    "thid": "acfb8c35-e8a4-43d8-bdf8-0242b796a386"
  },
  "status": "OK"
}
```

**Comment by jleach** [comment]
Because the wallet (Build 185) is working as expected with these demos I'm going to move the issue to `Done`.

**Comment by knguyenBC** [comment]
Basically, it's not a wallet thing but issues with the demos.
