### ISSUE TITLE
"Unlock" and "Unlock with biometrics" buttons are covered by the keyboard

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#666]
As a user, I want to be able to close the keyboard so that I can tap on the buttons that are hidden from the keyboard

### **Acceptance criteria**
Given the mobile keyboard is open
When the user taps an empty space outside the keyboard
Then the keyboard closes

### Screenshots showing issue
Initial screen with the keyboard covering the buttons:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1348549/197273688-f5ecaae8-2864-4580-8236-23d9f56e33df.png)

Screen after the PIN is entered, the buttons are now visible:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1348549/197273714-bd3206f9-e824-4d8a-be59-ff89f70477d9.png)

**Comment by knguyenBC** [comment]
Updated the ticket to include expected on the behaviour of the keyboard.

**Comment by bryce-mcmath** [comment]
The current state of this appears a bit different, at least on Android. Here is what it looks like with the keyboard active:![Screenshot 2023-02-07 at 4.04.24 PM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/1bc2b25c-0a54-426c-beac-d552103dcc23)

And here is what it looks like with the keyboard dismissed:![Screenshot 2023-02-07 at 4.04.44 PM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/7715f264-c465-4a5f-8039-ccee8d2f5cd6)

Should I make it so that the buttons are always in the same place  at the bottom of the view (beneath keyboard) and that the keyboard dismisses whenever a user taps outside of the keyboard in a blank space? I think this seems like the best approach but just want to get someone else's opinion

**Comment by knguyenBC** [comment]
That behaviour is good. I think the issue this ticket was focusing on was the fact that the keyboard was not, at the time, dismissable when a user tapped outside of the keyboard. Is the behaviour the same in iOS?

**Comment by bryce-mcmath** [comment]
The keyboard is still only dismissible by pressing the back button on Android. As for the behaviour on iOS I'll have to defer to Clecio, Jason, or Akiff.

**Comment by cvarjao** [comment]
The keyboard is still covering. I am using iPhone 7 with a small screen size. The keyboard is dismissible by tapping outside, but I also thought that the screen should still be scrollable.

**Comment by cvarjao** [comment]
https://images.zenhubusercontent.com/429950091/10872f13-01ca-47f5-9eec-568d7c6af3f2/unlock_screen.mov

**Comment by bryce-mcmath** [comment]
Interesting. So the behaviour on Android is the buttons sliding up above the keyboard, but not on iOS. On Clecio's recommendation I tried with max zoom and font size, here is what it looks like on Android when the keyboard is up:![Screenshot 2023-02-08 at 11.59.52 AM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/1901bf29-a8c2-4d54-9f4d-78c236857707)
 
So I think we should unify both to have the buttons stay in position (like they do on iOS) and then make the keyboard dismissible by tapping on any empty space outside of the keyboard.
