### ISSUE TITLE
Display Credential Offer

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#79]
As a holder I need to approve any offered credential so I feel in control of my wallet.

### Wireframes

Hi-Fi wireframes
https://xd.adobe.com/view/3db881d4-e963-42ec-a2c4-6b5ca23862a3-68eb/

https://xd.adobe.com/view/efd8f0c6-3ba0-436e-b72c-2dad62569aa2-ba8b/screen/8ae142a3-e175-4f2c-b59f-ac0d4e4f7a32

**Scenario: Holder receives a credential offer**
Given the holder has a connection with an issuer
When the issuer sends a credential offer
Then the credential offer will arrive in the form of a notification in the home screen

**Scenario: Holder selects a credential offer**
Given the holder has received a credential offer from a connected issuer
When the holder selects on the credential offer
Then the holder is taken to the credential offer screen/flow

**Scenario: Holder accepts a credential offer**
Given the holder selects a credential offer
When the holder accepts the credential offer
Then the holder will be taken to a "credential is on the way" loading screen

Given the holder accepts a credential offer from an issuer they are connected with
When the credential arrives in the wallet
Then the "credential is on the way" screen will change to the "Credential added to your wallet" success screen
And a Done button.

Given the holder accepts a credential offer from an issuer they are connected with
When the holder selects "Done"
Then the screen moves to the credential list page

**Scenario: Holder declines a credential offer**
Given the holder selects a credential offer
When the holder declines the credential offer
Then the holder will be taken to the credential list page
And a temporary notification will appear that informs the holder of the declined action

**Comment by jleach** [comment]
@knguyenBC A few ways I deviated from the designs (and why):

- We don't have any branding (logo) ATM so I just re-used the first letter of the issuer like we did in credential list
- We don't have a great way to show who issued the credential (yet) so I've used what exists now until we figure out a better way;
- I removed the duplicates of usage of branding. In the design we have the logo at the top, then just below. Not sure if duplicating them so close adds much but LMK if you want it as per the designs;
- I changed "Issued: Pending" to "Issued: Jan 21, 222". Since its an "offer" that is not yet accepted "Pending" seems implied to me also, a date fits better with the word "Issued". LMK if Pending is what you want. It'll be hard coded as an offer is always "Pending" until a following screen (After they hit Accept or Decline). Otherwise the only state that comes from a credential is `  "state": "offer-received"` 


![IMG_4451E58CF5CB-1.jpeg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/dec5857c-64dd-484b-b3d0-baaee4b2ca0c)

**Comment by knguyenBC** [comment]
@jleach 
First two points: a-okay
3rd point: a-okay for now. Makes sense since there isn't any branding yet but later, we might need to revisit once branding is available. 
4th point: the pending label from the designs comes from a misconception of issued date. The field for issued date should be the date that the credential offer was generated by the issuer. So it shouldn't say "Pending" it should use the createdAt property of the credential.
