### ISSUE TITLE
Publish Code Coverage Results

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#805]

**Comment by jleach** [comment]
Looked into this issue. The unit tests run in the Bifold repo but it does not run CodeCoverage which would slurp up and report on the results as one of the automated "checks". Typically a check would be "did this pr did not decrease the code coverage". I don't think running this in our repo is the right thing to do because its not where issues will be fixed.

**Comment by jleach** [comment]
@cvarjao Are you able to check if you can add checks / bots to the Bifold repo? I cannot. If you can't I'll need to ask one of the Hyperledger admins to help.

**Comment by cvarjao** [comment]
> @cvarjao Are you able to check if you can add checks / bots to the Bifold repo? I cannot. If you can't I'll need to ask one of the Hyperledger admins to help.

I am not an organization admin, so you might need someone from hyperledger

**Comment by swcurran** [comment]
Clecio — you are an admin — or at least you are on the “Aries Mobile Agent React Native admins” team.

**Comment by jleach** [comment]
The CodeCov is being reported now, sample here in one of [my PRs](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/868).
