### ISSUE TITLE
Credential Offer Cancel

### ISSUE THREAD

**Issue by amanji** [bcgov/bc-wallet-mobile#83]
AS A holder, I WANT the ability to abandon the issue credential process, SO THAT I can go onto something else, or make me feel in control if its taking too long

Note: If the issuance or verification process is prone to take a long time and leave users feeling stuck this might be an issue

#### Scenario: Holder Cancels the Connection Request
Given the holder has scanned a QR code invitation
And is waiting for the connection to be established
When the holder selects "cancel"
Then they are brought back to home screen

#### Scenario: Holder Cancels the Credential Offer
Given the holder has scanned a QR code invitation
And has the connection established with the issuer
And a credential offer has been received
And a credential offer has been accepted
And is waiting for the credential to be issued
When the holder taps on "cancel"
Then a temporary notification (toast) is displayed stating the transaction has been cancelled
And they are brought back to home screen

#### Scenario: Holder leaves the credential offering flow
Given holder is waiting to receive the credential
When the holder <leaves the flow>
Then a notification is displayed when the credential is received

Examples:
| leaves the flow |
| clicks on the home button |
| leaves the app |

**Comment by nodlesh** [comment]
@cvarjao I think you asked me to complete or clean this up. I can't edit the ticket, so here it is in the comments. We still need to review together of course and answer that question I have embedded. 

~As a holder I need the ability to take action if any part of the receiving process is taking too long so I can retry or abandon as I choose.~
AS A holder, I WANT the ability to abandon the issue credential process, SO THAT I can go onto something else, or make me feel in control if its taking too long

### Acceptance Criteria:


#### Scenario: Holder Cancels the Connection Request
Given the holder has scanned a QR code invitation
And is waiting for the connection to be established
When the holder selects "cancel"
Then they are brought back to home screen

#### Scenario: Holder Cancels the Credential Offer
Given the holder has scanned a QR code invitation
And has the connection established with the issuer
And a credential offer has been received
And a credential offer has been accepted
And is waiting for the credential to be issued
When the holder taps on "cancel"
Then a temporary notification (toast) is displayed stating the transaction has been cancelled
And they are brought back to home screen

#### Scenario: Holder Cancels the Credential Offer taking longer than 10 seconds
Given the holder has accepted a credential offer
And they are waiting to receive the credential
When the process takes over 10 seconds
And a message saying that "it is taking longer than usual" is shown
And the holder selects "cancel"
Then a temporary notification (toast) is displayed stating the transaction has been cancelled
And they are brought back to home screen

#### Scenario: Holder Waits for the Credential Offer taking longer than 10 seconds
Given the holder has accepted a credential offer
And they are waiting to receive the credential
And the process is taking more than 10 seconds
When the process takes over 10 seconds
And a message saying that "it is taking longer than usual" is shown
And the holder selects "continue?"
Then they continue to wait until the credential is issued (Q: Will they get another option to cancel if it takes another 10 seconds?)
And a notification is displayed when the credential is received

#### Scenario: Holder leaves the credential offering flow
Given holder is waiting to receive the credential
When the holder <leaves the flow>
Then a notification is displayed when the credential is received

Examples:
| leaves the flow |
| clicks on the home button |
| leaves the app |

**Comment by amanji** [comment]
Can this be closed?

**Comment by amanji** [comment]
> Can this be closed?

**Comment by cvarjao** [comment]
closing stale issues
