### ISSUE TITLE
Long delay between tapping "unlock" and seeing wait screen with tips

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#862]
Current Experience:
https://user-images.githubusercontent.com/1348549/215220496-cd242614-4707-4c1c-ae97-144c36d38bc2.mov

Acceptance Criteria
- When tapping "unlock" the user should see the "loading" screen as soon as possible
- if the PIN is incorrect, the "loading" screen is hidden, the "enter PIN" screen is displayed with some message about the PIN being incorrect

Notes:
- The delayed is attached to the wallet key hash validation and unlocking of the wallet by AFJ

**Comment by nodlesh** [comment]
I just wanted to take a stab at the User Story and Gherkin Acceptance Criteria for this one. 

AS A BC Wallet Credential Holder,
I WANT opening the app to a ready state to be as smooth and quick as possible, 
SO THAT I feel confident the app is stable, well designed, and I don't question the apps ability to do the things I really need the app to do for me.

```gherkin
Given the user is <opening BC Wallet>
When they authenticate in the app
Then there is no perceivable delay between authenticating and initializing the app

Examples:
   | opening the app |
   | first opening and onboarding |
   | already onboarded and opening the closed app |
   | already onboarded and opening a backgrounded app |
```

I don't understand the second point in the Acceptance Criteria.  Sounds like a bug if it doesn't do that by default.

**Comment by cvarjao** [comment]
we haven't noticed this behaviour anymore
