### ISSUE TITLE
Update mediator in dev to 1.0.7-rc1

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#910]
Update the mediator in our dev environment to test fixing [625](https://github.com/hyperledger/aries-mobile-agent-react-native/issues/625).

**Comment by jleach** [comment]
@wadeking98 I updated dev yesterday by building the image locally and pushed it to the OCP image registry. I'm not sure why the on-cluster build did not update to 1.0.7-rc1. It just went to 0.8.x.

**Comment by jleach** [comment]
@wadeking98 I updated dev yesterday by building the image locally and pushed it to the OCP image registry. I'm not sure why the on-cluster build did not update to 1.0.7-rc1. It just went to 0.8.x.

**Comment by WadeBarnes** [comment]
The mediator build is building a custom ACA-py image that is just pulling and installing the latest code from the main branch of the ACA-py repo.  It, and the aries-mediator-service itself, should be updated to use the new [ACA-py container images](https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python) as the base images. 
 Introduced with the release of [ACA-py v0.8.0-rc0](https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.8.0-rc0); the latest `aca-py` release.

**Comment by WadeBarnes** [comment]
@jleach, It's saying `v1.0.7-rc1` in this ticket, but the agent is listing `v1.0.0-rc1`, and since the image was built outside of OpenShift we don't have the BUILD variable of image meta data containing the git rev we could use to verify exactly which version of the code is contained in the image.  How did you identify the version of code to use for the build?
