### ISSUE TITLE
Proof Request with multiple attributes from one credential shows as coming from separate credentials

### ISSUE THREAD

**Issue by nodlesh** [bcgov/bc-wallet-mobile#975]
### Steps to Reproduce

``` gherkin
Given I have one credential
When I receive a proof request with multiple (3) attributes from this one credential
Then the messaging is telling me it is taking it from multiple (3) credentials
```

![Screenshot 2023-03-14 at 10.52.42 AM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/653f96a3-3e56-4926-9f92-aeefa94f89a4)

This credential and proof request comes from the following:
https://openvp-candy-issuer-test.apps.silver.devops.gov.bc.ca/
https://pctftest-test.vonx.io/

### Expected Result
It should state that "A contact is requesting the following information from 1 credential"

 
### Environment
BC Wallet build 743
Tested iOS 15

### Workaround
None known

### Severity
Medium

### Priority
Medium

### Test Impact
T009-Proof

**Comment by swcurran** [comment]
This is likely because of the design of the presentation request — e.g. that the presentation request is allowing for the values to come from 3 different credentials, even though they could be coming from one.  The presentation request could be designed to group the request so all three must come from the same credential — it is up to the verifier.  In most cases the verifier would design their presentation request better.  Visually:

The verifier asked for:

- Attrib1: Name(“given_names”)
- Attrib2: Name(“family_name”)
- Attrib3: Name(“region”)

But could have asked for:

- Attrib1: Names(“given_names”, “family_name”, “region”)

That said, the wallet could get trickier/smarter and merge the sets of claims that are going to be source from the same credential and show them that way.  The code would have to process all the groups within the presentation to check if they are from the same source credential as other groups.  Possible, but questionable if you want to do that.

**Comment by esune** [comment]
For reference, the proof-configuration is this: https://github.com/esune/essential-services-delivery/blob/master/proof-configurations/verified-person/unverified-person.json
@swcurran is correct about the three attributes being specified separately - this is the "older" style proof-request (we could not specify the `names` array when the proof was initially designed and used the first time). I agree with him that the wallet should ideally be able to detect this as there is no guarantee a verifier will compile the proof using the `names` array rather than individually named attributes.

**Comment by wadeking98** [comment]
this issue is now resolved by https://github.com/hyperledger/aries-mobile-agent-react-native/pull/661

**Comment by nodlesh** [comment]
Verified fixed in build 807.
