### ISSUE TITLE
Spike: Survey/Feedback collection tool

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#980]
Explore:
- Embedding vs External Link depending on tools

### SurveyMonkey (embedded link)
Instructions (copied from survey monkey):
Follow these basic steps to integrate the SurveyMonkey Mobile SDK directly into your mobile app:

Download the SurveyMonkey [iOS SDK](https://www.surveymonkey.com/collect/log_redirects?sm=q4mZ8kHs_2FjhbuxQ7ENKvI0tv_2FkFcnMQqakDs2tVSqIzzQhjICXQkkUPJ4OE4NXv4o5iKZhjsjI_2FpFLCG78Hr6QHAb06bIm2N5SpcDnzY_2BiUCQLPHJG60bEmy5TaHnRKQ) or [Android SDK](https://www.surveymonkey.com/collect/log_redirects?sm=SMuIIYM1HJSXcAOeEQ0D0_2Fu0arln693gqDkpy50IGTI15uj0LLg4dZpH0MN0BtHLf22saoV7dN5dWgmSeci6jMTNLU7cHCPmCKvfEfVEzXKLksASgoYHWd1Oep6iaU4P) in Github
Copy the survey hash below into your Xcode or Android Studio project where you initialize the SDK

Suvey hash: SJ2RB66

### **Other tools if imbed doesn't work:**
   - CHEFS/SUBMIT
   - others

**Comment by bryce-mcmath** [comment]
I think our best approach is to use a simple [web link](https://help.surveymonkey.com/en/surveymonkey/send/web-link-collector/) to open our survey in the default browser (not in-app). 

Because we're using React Native the Survey Monkey-provided SDKs for Android and iOS won't work, and the only RN option for SurveyMonkey (https://github.com/yarikpwnzer/react-native-survey-monkey) is deprecated and no longer maintained. It's last supported version of RN was before ours and the maintainers aren't replying to messages. Survey Monkey also offers an API but that would be an expensive and very time consuming option, I also don't think we want our app making random web requests like that.

**Comment by jleach** [comment]
@cvarjao @knguyenBC I agree with @bryce-mcmath thoughts above. Shall we close this issue and try a web link to open an in-browser survey to unblock #1002 (part of this sprint)?

**Comment by knguyenBC** [comment]
I think that's fine.

**Comment by jleach** [comment]
Chatted with @cvarjao @knguyenBC and we decided to revive the WebView to make this web form look like its part of the app rather than handing off to a web browser. Closing.
